# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-08 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0002_auto_20160930_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizeURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='自定义URL')),
                ('target_url', models.CharField(blank=True, max_length=1024, null=True, verbose_name='目标URL')),
                ('module', models.CharField(blank=True, max_length=1024, null=True, verbose_name='内部模块名称')),
                ('function', models.CharField(blank=True, max_length=1024, null=True, verbose_name='内部模块方法')),
                ('type', models.CharField(blank=True, max_length=10, null=True, verbose_name='跳转方式')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '自定义URL',
                'verbose_name_plural': '自定义URL',
            },
        ),
    ]
