# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-10 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0003_customizeurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='express_type_id',
            field=models.IntegerField(default=0, verbose_name='快递方式ID'),
        ),
    ]
