# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0004_order_express_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='express',
            name='price_fixed',
            field=models.FloatField(default=0.0, verbose_name='固定运费'),
        ),
        migrations.AlterField(
            model_name='express',
            name='price_per_kilogram',
            field=models.FloatField(default=0.0, verbose_name='每千克运费'),
        ),
        migrations.AlterField(
            model_name='expresstype',
            name='price_fixed',
            field=models.FloatField(default=0.0, verbose_name='固定运费'),
        ),
        migrations.AlterField(
            model_name='expresstype',
            name='price_per_kilogram',
            field=models.FloatField(default=0.0, verbose_name='每千克运费'),
        ),
    ]
