# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-28 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0005_auto_20161019_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='分类描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categorys',
            field=models.ManyToManyField(related_name='products', to='shopcart.Category', verbose_name='商品分类'),
        ),
    ]
