# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-03 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0006_auto_20161128_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBusiCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='分类名称')),
                ('code', models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='分类代码')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序序号')),
                ('keywords', models.CharField(blank=True, max_length=254, null=True, verbose_name='关键字')),
                ('page_title', models.CharField(blank=True, default='', max_length=100, verbose_name='网页标题')),
                ('static_file_name', models.CharField(blank=True, db_index=True, max_length=254, null=True, unique=True, verbose_name='静态文件名')),
                ('short_desc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='简略描述')),
                ('category_template', models.CharField(blank=True, default='', max_length=254, verbose_name='分类指定模板')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '文章业务分类',
                'verbose_name': '文章业务分类',
            },
        ),
        migrations.CreateModel(
            name='ClientMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='菜单用途')),
                ('code', models.CharField(max_length=100, null=True, verbose_name='菜单代码')),
                ('content', models.TextField(blank=True, null=True, verbose_name='菜单内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name_plural': '菜单信息',
                'verbose_name': '菜单信息',
            },
        ),
        migrations.CreateModel(
            name='CustomizeVar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64, null=True, verbose_name='变量名称')),
                ('value', models.CharField(max_length=254, null=True, verbose_name='变量值')),
                ('desc', models.CharField(max_length=254, null=True, verbose_name='变量描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name_plural': '自定义变量',
                'verbose_name': '自定义变量',
            },
        ),
        migrations.CreateModel(
            name='ProductPara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='参数名称')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '商品参数定义',
                'verbose_name': '商品参数定义',
            },
        ),
        migrations.CreateModel(
            name='ProductParaDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=254, verbose_name='参数值')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '商品参数具体数值',
                'verbose_name': '商品参数具体数值',
            },
        ),
        migrations.CreateModel(
            name='ProductParaGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='参数组名称')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '商品参数组定义',
                'verbose_name': '商品参数组定义',
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序序号')),
                ('price', models.FloatField(default=0.0, verbose_name='价格')),
                ('quantity', models.IntegerField(default=0, verbose_name='数量区间')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '商品分段价格',
                'verbose_name': '商品分段价格',
            },
        ),
        migrations.CreateModel(
            name='ProductPush',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序序号')),
                ('title', models.CharField(default='', max_length=254, null=True, verbose_name='定制的标题')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name_plural': '商品推荐',
                'verbose_name': '商品推荐',
            },
        ),
        migrations.CreateModel(
            name='ProductPushGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='推送组名称')),
                ('code', models.CharField(max_length=100, null=True, verbose_name='推送组代码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name_plural': '商品推荐组',
                'verbose_name': '商品推荐组',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='幻灯用途')),
                ('code', models.CharField(max_length=100, null=True, verbose_name='幻灯代码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name_plural': '幻灯信息',
                'verbose_name': '幻灯信息',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='alt_value',
            field=models.CharField(default='', max_length=100, verbose_name='Alt值'),
        ),
        migrations.AddField(
            model_name='album',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='文件名'),
        ),
        migrations.AddField(
            model_name='album',
            name='href',
            field=models.CharField(default='', max_length=254, verbose_name='自定义链接地址'),
        ),
        migrations.AddField(
            model_name='album',
            name='path',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='文件路径'),
        ),
        migrations.AddField(
            model_name='album',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='排序序号'),
        ),
        migrations.AddField(
            model_name='album',
            name='thumb_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='文件名'),
        ),
        migrations.AddField(
            model_name='article',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序序号'),
        ),
        migrations.AddField(
            model_name='customizeurl',
            name='is_customize_tdk',
            field=models.BooleanField(default=False, verbose_name='是否自定义TDK'),
        ),
        migrations.AddField(
            model_name='customizeurl',
            name='keywords',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='关键字'),
        ),
        migrations.AddField(
            model_name='customizeurl',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='页面名称'),
        ),
        migrations.AddField(
            model_name='customizeurl',
            name='page_name',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='页面标题'),
        ),
        migrations.AddField(
            model_name='customizeurl',
            name='short_desc',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='简略描述'),
        ),
        migrations.AddField(
            model_name='express',
            name='price_per_stere',
            field=models.FloatField(default=0.0, verbose_name='每立方米运费'),
        ),
        migrations.AddField(
            model_name='expresstype',
            name='price_calc_type',
            field=models.CharField(default='fixed', max_length=10, verbose_name='运费计算方式'),
        ),
        migrations.AddField(
            model_name='expresstype',
            name='price_per_stere',
            field=models.FloatField(default=0.0, verbose_name='每立方米运费'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='product',
            field=models.IntegerField(default=0, verbose_name='关联商品的id'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='留言标题'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='unit',
            field=models.CharField(max_length=100, null=True, verbose_name='数量单位'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_ip',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='最后登陆IP地址'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='reg_ip',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='注册IP地址'),
        ),
        migrations.AddField(
            model_name='order',
            name='price_adjusment',
            field=models.FloatField(default=0.0, verbose_name='管理员调整价格'),
        ),
        migrations.AddField(
            model_name='order',
            name='promotion_code',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='使用的优惠码'),
        ),
        migrations.AddField(
            model_name='product',
            name='cuboid_height',
            field=models.FloatField(default=0.0, verbose_name='体积_高_毫米'),
        ),
        migrations.AddField(
            model_name='product',
            name='cuboid_long',
            field=models.FloatField(default=0.0, verbose_name='体积_长_毫米'),
        ),
        migrations.AddField(
            model_name='product',
            name='cuboid_width',
            field=models.FloatField(default=0.0, verbose_name='体积_宽_毫米'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='B2C', max_length=20, verbose_name='商品类型'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0.0, verbose_name='重量，克'),
        ),
        migrations.AddField(
            model_name='product',
            name='youtube',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='youtube视频地址'),
        ),
        migrations.AddField(
            model_name='product_images',
            name='alt_value',
            field=models.CharField(default='', max_length=100, verbose_name='Alt值'),
        ),
        migrations.AddField(
            model_name='product_images',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='文件名'),
        ),
        migrations.AddField(
            model_name='product_images',
            name='path',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='文件路径'),
        ),
        migrations.AddField(
            model_name='product_images',
            name='thumb_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='文件名'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='name',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='促销码名称'),
        ),
        migrations.AlterField(
            model_name='article',
            name='static_file_name',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='静态文件名'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', '等待付款'), ('5', '已付款未确认'), ('10', '已付款'), ('15', '已备货'), ('18', '部分发货'), ('20', '已发货'), ('30', '已完成'), ('40', '已取消'), ('90', '订单异常'), ('99', '订单已关闭')], default='0', max_length=32, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='product',
            name='static_file_name',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=254, null=True, verbose_name='静态文件名(不包含路径，以html结尾)'),
        ),
        migrations.AlterField(
            model_name='product_attribute',
            name='price_adjusment',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='productpush',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shopcart.ProductPushGroup'),
        ),
        migrations.AddField(
            model_name='productpush',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_channels', to='shopcart.Product'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='shopcart.Product', verbose_name='关联的商品'),
        ),
        migrations.AddField(
            model_name='productparadetail',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='shopcart.Product', verbose_name='宿主商品'),
        ),
        migrations.AddField(
            model_name='productparadetail',
            name='product_para',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopcart.ProductPara'),
        ),
        migrations.AddField(
            model_name='productpara',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paras', to='shopcart.ProductParaGroup'),
        ),
        migrations.AddField(
            model_name='article',
            name='busi_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='shopcart.ArticleBusiCategory', verbose_name='文章业务分类'),
        ),
    ]
