# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-30 08:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0007_auto_20170503_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeEmailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '通知邮件列表',
                'verbose_name_plural': '通知邮件列表',
            },
        ),
        migrations.CreateModel(
            name='NoticeEmailType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=64, null=True, verbose_name='通知类型')),
                ('name', models.CharField(default='', max_length=64, null=True, verbose_name='通知名称')),
                ('is_send', models.BooleanField(default=False, verbose_name='是否发送')),
                ('title', models.CharField(max_length=254, verbose_name='邮件主题')),
                ('sender', models.EmailField(max_length=254, null=True)),
                ('smtp_host', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('need_ssl', models.BooleanField(default=False, verbose_name='是否启用SSL连接')),
                ('template', models.CharField(blank=True, max_length=254, null=True, verbose_name='模板组名称')),
                ('template_file', models.CharField(blank=True, max_length=254, null=True, verbose_name='模板文件名称')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '通知邮件类型',
                'verbose_name_plural': '通知邮件类型',
            },
        ),
        migrations.CreateModel(
            name='OAuthAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='', max_length=64, null=True, verbose_name='社交网站')),
                ('uid', models.CharField(default='', max_length=64, null=True, verbose_name='UID')),
                ('name', models.CharField(default='', max_length=128, null=True, verbose_name='昵称')),
                ('avatar', models.CharField(default='', max_length=1024, null=True, verbose_name='头像')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '社交账户账号',
                'verbose_name_plural': '社交账户账号',
            },
        ),
        migrations.CreateModel(
            name='OAuthSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64, null=True, verbose_name='名称')),
                ('impl_class', models.CharField(default='', max_length=256, null=True, verbose_name='实现类')),
                ('redirect_uri', models.CharField(default='', max_length=256, null=True, verbose_name='返回网址')),
                ('client_id', models.CharField(default='', max_length=256, null=True, verbose_name='客户ID')),
                ('client_secret', models.CharField(default='', max_length=256, null=True, verbose_name='客户密钥')),
                ('scope_login', models.CharField(default='', max_length=256, null=True, verbose_name='Login资料范围代码')),
                ('scope_info', models.CharField(default='', max_length=256, null=True, verbose_name='Userinfo资料范围代码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '社交账户登陆配置',
                'verbose_name_plural': '社交账户登陆配置',
            },
        ),
        migrations.CreateModel(
            name='OrderCustRemark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='留言内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cust_remarks', to='shopcart.Order')),
            ],
            options={
                'verbose_name': '订单客户留言',
                'verbose_name_plural': '订单客户留言',
            },
        ),
        migrations.AddField(
            model_name='email',
            name='need_ssl',
            field=models.BooleanField(default=False, verbose_name='是否启用SSL连接'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_desc',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='简略描述'),
        ),
        migrations.AlterField(
            model_name='category',
            name='short_desc',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='简略描述'),
        ),
        migrations.AlterField(
            model_name='order_products',
            name='short_desc',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=100, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_desc',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='简略描述'),
        ),
        migrations.AddField(
            model_name='noticeemaillist',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditors', to='shopcart.NoticeEmailType', verbose_name='类型'),
        ),
    ]
