# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-30 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0008_auto_20170830_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_2',
            field=models.TextField(blank=True, verbose_name='详细描述_2'),
        ),
    ]
