# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-31 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0009_product_description_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(max_length=100, null=True, verbose_name='手机号'),
        ),
    ]
