# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-31 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0010_inquiry_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImportError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_num', models.IntegerField(default=0, verbose_name='行号')),
                ('type', models.CharField(default='B2C', max_length=20, verbose_name='商品类型')),
                ('name', models.CharField(db_index=True, default='', max_length=100, verbose_name='商品名称')),
                ('item_number', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='商品编号')),
                ('static_file_name', models.CharField(blank=True, db_index=True, default=None, max_length=254, null=True, verbose_name='静态文件名(不包含路径，以html结尾)')),
                ('short_desc', models.CharField(blank=True, default='', max_length=1024, verbose_name='简略描述')),
                ('cat_str', models.CharField(blank=True, default='', max_length=1024, verbose_name='分类名称')),
                ('keywords', models.CharField(blank=True, default='', max_length=254, verbose_name='关键字')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序序号')),
                ('is_publish', models.BooleanField(default=False, verbose_name='上架')),
                ('market_price', models.FloatField(default=0.0, verbose_name='市场价')),
                ('price1', models.FloatField(default=0.0, verbose_name='区间价1')),
                ('quantity1', models.IntegerField(default=0, verbose_name='下单量1')),
                ('price2', models.FloatField(default=0.0, verbose_name='区间价2')),
                ('quantity2', models.IntegerField(default=0, verbose_name='下单量2')),
                ('price3', models.FloatField(default=0.0, verbose_name='区间价3')),
                ('quantity3', models.IntegerField(default=0, verbose_name='下单量3')),
                ('description', models.TextField(blank=True, verbose_name='详细描述')),
                ('image1', models.CharField(blank=True, default='', max_length=1024, verbose_name='图片1')),
                ('image2', models.CharField(blank=True, default='', max_length=1024, verbose_name='图片2')),
                ('image3', models.CharField(blank=True, default='', max_length=1024, verbose_name='图片3')),
                ('image4', models.CharField(blank=True, default='', max_length=1024, verbose_name='图片4')),
                ('image5', models.CharField(blank=True, default='', max_length=1024, verbose_name='图片5')),
                ('folder_local', models.CharField(blank=True, default='', max_length=1024, verbose_name='图片目录名称')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '导入异常的记录',
                'verbose_name': '导入异常的记录',
            },
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_2',
        ),
    ]
