# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-21 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0011_auto_20170831_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchTaskMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=20, unique=True, verbose_name='任务类型')),
                ('status', models.CharField(default='created', max_length=20, verbose_name='任务状态')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功记录数')),
                ('failed_count', models.IntegerField(default=0, verbose_name='失败记录数')),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '批量任务监控',
                'verbose_name': '批量任务监控',
            },
        ),
    ]
