# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-21 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0012_batchtaskmonitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdf',
            field=models.URLField(default=3, verbose_name='pdf'),
            preserve_default=False,
        ),
    ]
