# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-21 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0013_product_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdf_thumb',
            field=models.URLField(default=3, verbose_name='pdf的缩略图'),
            preserve_default=False,
        ),
    ]
