# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-22 01:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0015_auto_20171121_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_pdf',
            name='product_pdf',
        ),
        migrations.DeleteModel(
            name='Product_pdf',
        ),
    ]
