# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-22 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0016_auto_20171122_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.URLField(null=True)),
                ('image', models.URLField(null=True)),
                ('is_show_in_product_detail', models.BooleanField(default=False, verbose_name='是否在商品详情中展示')),
                ('sort', models.IntegerField(default=0, verbose_name='排序序号')),
                ('alt_value', models.CharField(default='', max_length=100, verbose_name='Alt值')),
                ('file_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件名')),
                ('thumb_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件名')),
                ('path', models.CharField(blank=True, max_length=254, null=True, verbose_name='文件路径')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='shopcart.Product', verbose_name='关联的商品pdf')),
            ],
            options={
                'verbose_name': '商品pdf相册',
                'verbose_name_plural': '商品pdf相册',
            },
        ),
    ]
