# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-23 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0017_product_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_pdf',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product_pdf',
        ),
    ]
