# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-04 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0018_auto_20171123_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=254, null=True, verbose_name='标题')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序序号')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('keywords', models.CharField(blank=True, max_length=254, null=True, verbose_name='关键字')),
                ('page_title', models.CharField(blank=True, default='', max_length=100, verbose_name='网页标题')),
                ('short_desc', models.CharField(blank=True, default='', max_length=1024, verbose_name='简略描述')),
                ('static_file_name', models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='静态文件名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
        ),
    ]
