# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-04 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0019_recruiting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recruiting',
            new_name='Recruit',
        ),
    ]
