# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-06 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0021_auto_20171206_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='static_file_name',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='静态文件名'),
        ),
    ]
