# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-08 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0023_visitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='update_time',
        ),
        migrations.AddField(
            model_name='visitor',
            name='ip_address',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='IP地址'),
        ),
    ]
