# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-18 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0025_remove_visitor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_publish',
            field=models.BooleanField(default=True, verbose_name='上架'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(default='B2B', max_length=20, verbose_name='商品类型'),
        ),
    ]
