# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-18 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0026_auto_20171218_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_publish',
            field=models.BooleanField(default='1', verbose_name='上架'),
        ),
    ]
