# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-19 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0027_auto_20171218_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seo_desc',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='SEO描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='上架'),
        ),
    ]
