# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-20 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0028_auto_20171219_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='seo_desc',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(default='B2B+B2C', max_length=20, verbose_name='商品类型'),
        ),
    ]
