# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-27 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0029_auto_20171220_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=0, verbose_name='商品ID')),
                ('product_attribute_id', models.IntegerField(blank=True, null=True, verbose_name='SKU的id')),
                ('product_attribute_item_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU编号')),
                ('product_attribute_name', models.CharField(default='', max_length=1000, verbose_name='选中的商品属性文字说明')),
                ('name', models.CharField(default='', max_length=100, verbose_name='商品名称')),
                ('item_number', models.CharField(default='', max_length=100, verbose_name='商品编号')),
                ('short_desc', models.CharField(default='', max_length=1024)),
                ('thumb', models.URLField()),
                ('image', models.URLField()),
                ('quantity', models.IntegerField(default=0, verbose_name='订购数量')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('inquiry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Inquiry_Products', to='shopcart.Inquiry')),
            ],
            options={
                'verbose_name_plural': '询盘商品',
                'verbose_name': '询盘商品',
            },
        ),
    ]
