# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-27 08:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0030_inquiry_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiry', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
