# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-29 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0031_inquiry_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='菜单名称')),
                ('url', models.CharField(default='', max_length=100, verbose_name='菜单URL')),
                ('sort_order', models.CharField(default='', max_length=100, verbose_name='排序序号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='shopcart.Menu', verbose_name='上级分类')),
            ],
        ),
    ]
